define UBOOT_RUN_POST_RSYNC_SCRIPT
	$(BR2_TARGET_UBOOT_RUN_POST_RSYNC_HOOK_SCRIPT) "$(@D)"
endef

ifneq ($(call qstrip,$(BR2_TARGET_UBOOT_RUN_POST_RSYNC_HOOK_SCRIPT)),)
     UBOOT_POST_RSYNC_HOOKS += UBOOT_RUN_POST_RSYNC_SCRIPT
     UBOOT_POST_EXTRACT_HOOKS += UBOOT_RUN_POST_RSYNC_SCRIPT
endif


include $(sort $(wildcard $(BR2_EXTERNAL_EBK_READER_PATH)/package/*/*.mk))
